- name: My first play
  hosts: dev-nginx
  remote_user: root
  tasks:
    - name: Ping my hosts
      ansible.builtin.ping:
    - name: Print message
      ansible.builtin.debug:
        msg: Hello world